language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  # - nvm install --lts
  # - gem install bundler -2.1.4

  - yes | gem update --system --force
  - gem install bundler
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - rake db:create
  - rake db:schema:load
script:
  - rake test
  - rake test:system